### PR TITLE
Update home_page.dart

### PR DESCRIPTION
**Pull request by Darkchove**
Naming and formatting: Follow Dart naming conventions and use consistent formatting for better readability. For example, capitalize class names (HomePage instead of homepage) and use lowercase with underscores for variable and function names (current_page instead of currentPage).

Remove unnecessary imports: Only import the packages that are actually used in the code. In this case, workout_app/utils/app_version_checker.dart is imported but not used.

Make use of final variables: Since the pages list and the items list of the BottomNavigationBar are not modified, they can be declared as final variables outside the build method to avoid unnecessary re-creations on each rebuild.

Use const for static widget instances: The pages list contains widget instances that don't need to be recreated on each rebuild. You can mark them as const to improve performance.

Extract methods for readability: Move the logic of checking the app version and handling the bottom navigation bar tap into separate methods for better readability and maintainability.

### CODE REVIEW

**Comment by tinghaolai** [comment]
@Darkchove Thanks for your suggestion!

**Comment by PurkkaKoodari** [comment]
You might want to revert this. If nothing else is broken, the PR at least removed the call to `AppVersionChecker.instance.checkAppVersion` entirely...

The same user was sending broken/useless issues/PRs with minimal-but-seemingly-legit code changes to other repos, including ours, which is how I ended up noticing this PR.

**Comment by tinghaolai** [comment]
Hi, @PurkkaKoodari 

Thanks!
I've reviewed the code and noticed the part you mentioned.
Regarding the correct approach, I believe I should submit a change request for this pull request.
However, due to various reasons, I am not currently inclined to be too strict about it.
Nevertheless, I still really appreciate your advice!

**Comment by Darkchove** [comment]
im not spam n meant no harm, just new to whole shin dig but heh

**Pull request merged**
